version: '3.3'

services:
  database:
    image: mysql:8.1-oracle
    restart: "no"
    volumes:
      - db_data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: joomla
        MYSQL_USER: joomlaCMS
        MYSQL_PASSWORD: joomlaCMSpassword
    networks:
        - joomla5-network

  joomla:
    depends_on:
      - database
    image: joomla:5.0-php8.2-fpm-alpine
    ports:
      - "${JOOMLA_PORT}:80"
    restart: "no"
    container_name: joomla5
    volumes:
      - ./htdocs:/var/www/html
    environment:
        JOOMLA_DB_HOST: database:3306
        JOOMLA_DB_USER: joomlaCMS
        JOOMLA_DB_PASSWORD: joomlaCMSpassword
        JOOMLA_DB_NAME: joomla
    networks:
        - joomla5-network

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    restart: "no"
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root
    networks:
      - joomla5-network

  mailhog:
    image: mailhog/mailhog
    restart: "no"
    ports:
      - "${MAILHOG_SMTP_PORT}:1025"
      - "${MAILHOG_WEB_PORT}:8025"
    networks:
      - joomla5-network

networks:
    joomla5-network:
        driver: bridge
volumes:
    db_data: {}